import '../models/models.dart';

class MockDataService {
  static final MockDataService _instance = MockDataService._internal();
  factory MockDataService() => _instance;
  MockDataService._internal();

  final List<Tool> _tools = [
    Tool(
      id: '1',
      name: 'ChatGPT',
      description: "OpenAI's flagship assistant for writing, research, coding, and brainstorming. Trusted by millions for everyday tasks and complex workflows alike.",
      websiteUrl: 'https://chat.openai.com',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/OpenAI_Logo.svg/200px-OpenAI_Logo.svg.png',
      categoryId: '4',
      tags: ['chatbot', 'writing', 'research'],
      pricingType: PricingType.freemium,
      rating: 4.8,
      viewCount: 982311,
      isVerified: true,
      isFeatured: true,
      isTrending: true,
      keyFeatures: ['GPT-4o reasoning', 'Image + voice input', 'Custom GPTs', 'Code interpreter'],
      pros: ['Best-in-class quality', 'Huge plugin ecosystem', 'Fast responses'],
      cons: ['Paid for best models', 'Occasional hallucinations'],
      freeTierInfo: 'Limited access to GPT-5.5 Instant, limited messages and uploads',
      pricingPlans: [
        PricingPlan(name: 'Go', price: '\$0', period: 'Free', description: 'More access to GPT-5.5 Instant, more messages'),
        PricingPlan(name: 'Plus', price: '\$20', period: '/month', description: 'Advanced reasoning models, expanded messages and uploads'),
        PricingPlan(name: 'Pro', price: '\$200', period: '/month', description: '5x or 20x more usage, Pro reasoning with GPT-5.6 Sol Pro'),
      ],
      trialInfo: 'Free plan available, no credit card required',
      membershipBenefits: ['Advanced reasoning models', 'Expanded messages and uploads', 'More complex image creation', 'Expanded deep research', 'Projects, scheduled tasks, custom GPTs', 'Early access to new features'],
      plusDiscountPercent: 15,
      proDiscountPercent: 20,
      discountCodePlus: 'AIVERSE-CGPT-PLUS',
      discountCodePro: 'AIVERSE-CGPT-PRO',
      createdAt: DateTime(2024, 1, 1),
      updatedAt: DateTime(2024, 6, 1),
    ),
    Tool(
      id: '2',
      name: 'Midjourney',
      description: "Premium image generation known for painterly, cinematic outputs. Operates through Discord and a sleek new web app.",
      websiteUrl: 'https://midjourney.com',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Midjourney_Emblem.png',
      categoryId: '1',
      tags: ['art', 'image', 'design'],
      pricingType: PricingType.paid,
      rating: 4.7,
      viewCount: 712409,
      isVerified: true,
      isFeatured: true,
      isTrending: true,
      keyFeatures: ['v6 model', 'Style references', 'Variation grids', 'Upscaling'],
      pros: ['Gorgeous defaults', 'Consistent style', 'Active community'],
      cons: ['No free tier', 'Discord-first UX'],
      freeTierInfo: null,
      pricingPlans: [
        PricingPlan(name: 'Basic', price: '\$10', period: '/month', description: '3.3 hours Fast GPU time'),
        PricingPlan(name: 'Standard', price: '\$30', period: '/month', description: '15 hours Fast GPU time, Unlimited Relax'),
        PricingPlan(name: 'Pro', price: '\$60', period: '/month', description: '30 hours Fast GPU time, Stealth Mode'),
        PricingPlan(name: 'Mega', price: '\$120', period: '/month', description: '60 hours Fast GPU time, Max Concurrent'),
      ],
      trialInfo: 'No free trial available',
      membershipBenefits: ['Access to v6 model', 'Style references', 'Variation grids', 'Upscaling', 'Web app access'],
      plusDiscountPercent: 10,
      proDiscountPercent: 15,
      discountCodePlus: 'AIVERSE-MJ-PLUS',
      discountCodePro: 'AIVERSE-MJ-PRO',
      createdAt: DateTime(2024, 1, 15),
      updatedAt: DateTime(2024, 5, 20),
    ),
    Tool(
      id: '3',
      name: 'Claude',
      description: "Anthropic's assistant excels at long documents, careful reasoning, and code. Sonnet 4.5 is the daily driver for many developers.",
      websiteUrl: 'https://claude.ai',
      logoUrl: null,
      categoryId: '4',
      tags: ['chatbot', 'research', 'coding'],
      pricingType: PricingType.freemium,
      rating: 4.8,
      viewCount: 654105,
      isVerified: true,
      isFeatured: true,
      isTrending: true,
      keyFeatures: ['200K context', 'Artifacts', 'Computer use', 'Projects'],
      pros: ['Excellent writing', 'Long context', 'Safer outputs'],
      cons: ['Slower than GPT', 'Limited image gen'],
      freeTierInfo: 'Limited messages with Claude 3.5 Sonnet',
      pricingPlans: [
        PricingPlan(name: 'Pro', price: '\$20', period: '/month', description: '5x more usage, access to all models'),
        PricingPlan(name: 'Max', price: '\$100', period: '/month', description: '20x more usage, priority access'),
      ],
      trialInfo: 'Free plan available with limited usage',
      membershipBenefits: ['200K context window', 'All Claude models', 'Artifacts', 'Computer use', 'Projects', 'Priority access'],
      plusDiscountPercent: 12,
      proDiscountPercent: 18,
      discountCodePlus: 'AIVERSE-CLAUDE-PLUS',
      discountCodePro: 'AIVERSE-CLAUDE-PRO',
      createdAt: DateTime(2024, 2, 1),
      updatedAt: DateTime(2024, 6, 10),
    ),
    Tool(
      id: '4',
      name: 'Cursor',
      description: "A VS Code fork built around AI pair programming. Multi-file edits, agent mode, and tab-complete that actually feels magical.",
      websiteUrl: 'https://cursor.com',
      logoUrl: null,
      categoryId: '5',
      tags: ['editor', 'coding', 'agent'],
      pricingType: PricingType.freemium,
      rating: 4.9,
      viewCount: 489205,
      isVerified: true,
      isFeatured: true,
      isTrending: true,
      keyFeatures: ['Composer agent', 'Cmd-K edits', 'Codebase chat', 'Tab autocomplete'],
      pros: ['Fast iteration', 'Great UX', 'Multi-file edits'],
      cons: ['Pricing per request', 'Resource heavy'],
      freeTierInfo: 'Limited Agent requests, Limited Tab completions',
      pricingPlans: [
        PricingPlan(name: 'Pro', price: '\$20', period: '/month', description: 'Extended Agent limits, frontier models'),
        PricingPlan(name: 'Teams', price: '\$40', period: '/user/month', description: 'Centralized billing, team marketplace'),
        PricingPlan(name: 'Enterprise', price: 'Custom', period: '', description: 'Pooled usage, SCIM, audit logs'),
      ],
      trialInfo: 'Free Hobby plan available, no credit card required',
      membershipBenefits: ['Extended Agent limits', 'Frontier models', 'MCPs, skills, hooks', 'Cloud agents', 'Bugbot'],
      plusDiscountPercent: 20,
      proDiscountPercent: 25,
      discountCodePlus: 'AIVERSE-CURSOR-PLUS',
      discountCodePro: 'AIVERSE-CURSOR-PRO',
      createdAt: DateTime(2024, 3, 1),
      updatedAt: DateTime(2024, 6, 15),
    ),
    Tool(
      id: '5',
      name: 'Suno',
      description: "Type a prompt, get a full song with vocals. Suno is the leader in generative music for hobbyists and producers.",
      websiteUrl: 'https://suno.com',
      logoUrl: null,
      categoryId: '3',
      tags: ['music', 'audio', 'vocals'],
      pricingType: PricingType.freemium,
      rating: 4.6,
      viewCount: 387605,
      isVerified: false,
      isFeatured: true,
      isTrending: true,
      keyFeatures: ['Full-song generation', 'Custom lyrics', 'Stem separation'],
      pros: ['Realistic vocals', 'Easy to use'],
      cons: ['Limited free credits'],
      freeTierInfo: '50 credits daily, 10 songs/day, no commercial use',
      pricingPlans: [
        PricingPlan(name: 'Pro', price: '\$8', period: '/month', description: '2,500 credits/month, commercial use rights'),
        PricingPlan(name: 'Premier', price: '\$24', period: '/month', description: '10,000 credits/month, all features unlocked'),
      ],
      trialInfo: 'Free plan available, no credit card required',
      membershipBenefits: ['Commercial use rights', 'Advanced models (v5.5)', 'Stem separation', 'Priority queue', 'Custom voice training'],
      plusDiscountPercent: 15,
      proDiscountPercent: 20,
      discountCodePlus: 'AIVERSE-SUNO-PLUS',
      discountCodePro: 'AIVERSE-SUNO-PRO',
      createdAt: DateTime(2024, 2, 15),
      updatedAt: DateTime(2024, 5, 25),
    ),
    Tool(
      id: '6',
      name: 'Runway',
      description: "Gen-3 Alpha turns text and images into cinematic clips. The go-to for motion designers and indie filmmakers.",
      websiteUrl: 'https://runwayml.com',
      logoUrl: null,
      categoryId: '2',
      tags: ['video', 'motion', 'film'],
      pricingType: PricingType.freemium,
      rating: 4.6,
      viewCount: 342104,
      isVerified: false,
      isFeatured: true,
      isTrending: true,
      keyFeatures: ['Gen-3 model', 'Motion brush', 'Lip sync'],
      pros: ['State-of-the-art video', 'Pro toolset'],
      cons: ['Credits burn fast'],
      freeTierInfo: '125 one-time credits to explore',
      pricingPlans: [
        PricingPlan(name: 'Standard', price: '\$12', period: '/month', description: '625 credits/month, all AI models'),
        PricingPlan(name: 'Pro', price: '\$28', period: '/month', description: '2,250 credits/month, custom voices'),
        PricingPlan(name: 'Max', price: '\$76', period: '/month', description: '9,500 credits/month, credit rollover'),
      ],
      trialInfo: 'Free plan with 125 credits, no credit card required',
      membershipBenefits: ['Gen-4.5 and all AI models', '4K upscaling', 'No watermarks', 'Custom voices', 'Priority access'],
      plusDiscountPercent: 10,
      proDiscountPercent: 15,
      discountCodePlus: 'AIVERSE-RUNWAY-PLUS',
      discountCodePro: 'AIVERSE-RUNWAY-PRO',
      createdAt: DateTime(2024, 1, 20),
      updatedAt: DateTime(2024, 6, 5),
    ),
    Tool(
      id: '7',
      name: 'Perplexity',
      description: "Cited, sourced answers that replace half your Google searches. Pro adds frontier models and Spaces.",
      websiteUrl: 'https://perplexity.ai',
      logoUrl: null,
      categoryId: '9',
      tags: ['search', 'research'],
      pricingType: PricingType.freemium,
      rating: 4.6,
      viewCount: 432104,
      isVerified: true,
      isFeatured: true,
      isTrending: true,
      keyFeatures: ['Live citations', 'Pro Search', 'Spaces'],
      pros: ['Real sources', 'Fast'],
      cons: ['Sometimes shallow'],
      freeTierInfo: '5 Pro searches per day, standard search',
      pricingPlans: [
        PricingPlan(name: 'Pro', price: '\$20', period: '/month', description: 'Unlimited Pro searches, all AI models'),
      ],
      trialInfo: 'Free plan available with limited Pro searches',
      membershipBenefits: ['Unlimited Pro searches', 'All AI models (GPT-4, Claude)', 'Spaces for collaboration', 'API access'],
      plusDiscountPercent: 12,
      proDiscountPercent: 18,
      discountCodePlus: 'AIVERSE-PPLX-PLUS',
      discountCodePro: 'AIVERSE-PPLX-PRO',
      createdAt: DateTime(2024, 2, 10),
      updatedAt: DateTime(2024, 6, 12),
    ),
    Tool(
      id: '8',
      name: 'Flux',
      description: "Black Forest Labs' image model with photoreal quality and fast inference. Available via API and many UIs.",
      websiteUrl: 'https://blackforestlabs.ai',
      logoUrl: null,
      categoryId: '1',
      tags: ['image', 'open-source'],
      pricingType: PricingType.freemium,
      rating: 4.5,
      viewCount: 198404,
      isVerified: false,
      isFeatured: false,
      isTrending: true,
      keyFeatures: ['Pro and Schnell tiers', 'API access'],
      pros: ['Photoreal', 'Open weights'],
      cons: ['Setup needed'],
      createdAt: DateTime(2024, 4, 1),
      updatedAt: DateTime(2024, 6, 18),
    ),
    Tool(
      id: '9',
      name: 'ElevenLabs',
      description: "The standard for natural text-to-speech and voice cloning. Used in audiobooks, dubbing, and game development.",
      websiteUrl: 'https://elevenlabs.io',
      logoUrl: null,
      categoryId: '6',
      tags: ['voice', 'tts', 'cloning'],
      pricingType: PricingType.freemium,
      rating: 4.7,
      viewCount: 521405,
      isVerified: true,
      isFeatured: true,
      keyFeatures: ['Voice cloning', 'Multilingual', 'Studio editor'],
      pros: ['Most natural voices', '30+ languages'],
      cons: ['Costs scale with use'],
      freeTierInfo: '10,000 credits/month, ~10 minutes TTS',
      pricingPlans: [
        PricingPlan(name: 'Starter', price: '\$6', period: '/month', description: '30,000 credits/month, commercial license'),
        PricingPlan(name: 'Creator', price: '\$11', period: '/month', description: '121,000 credits/month, professional voice cloning'),
        PricingPlan(name: 'Pro', price: '\$99', period: '/month', description: '600,000 credits/month, 44.1kHz audio'),
        PricingPlan(name: 'Scale', price: '\$299', period: '/month', description: '1.8M credits/month, 3 workspace seats'),
      ],
      trialInfo: 'Free plan available, no credit card required',
      membershipBenefits: ['Commercial license', 'Voice cloning', 'Dubbing studio', 'Priority support', 'Team collaboration'],
      plusDiscountPercent: 10,
      proDiscountPercent: 15,
      discountCodePlus: 'AIVERSE-11LABS-PLUS',
      discountCodePro: 'AIVERSE-11LABS-PRO',
      createdAt: DateTime(2024, 1, 10),
      updatedAt: DateTime(2024, 6, 8),
    ),
    Tool(
      id: '10',
      name: 'Flow',
      description: "Flow is Google's AI-powered Image generation tool that creates cinematic Image from simple text prompts. It uses advanced AI models to generate high-quality visuals, making it ideal for content creators, marketers, filmmakers, and social media creators.",
      websiteUrl: 'https://labs.google/flow',
      logoUrl: null,
      categoryId: '1',
      tags: ['AI image generator', 'Google AI', 'Veo'],
      pricingType: PricingType.free,
      rating: 0.0,
      viewCount: 9,
      isNew: true,
      createdAt: DateTime(2024, 6, 1),
      updatedAt: DateTime(2024, 6, 20),
    ),
    Tool(
      id: '11',
      name: 'v0 by Vercel',
      description: "Describe a UI, get production-ready React + Tailwind. Push straight to Vercel.",
      websiteUrl: 'https://v0.dev',
      logoUrl: null,
      categoryId: '5',
      tags: ['ui', 'react', 'frontend'],
      pricingType: PricingType.freemium,
      rating: 4.6,
      viewCount: 142305,
      isTrending: true,
      keyFeatures: ['React + Tailwind', 'Iterate in chat', 'Shadcn-aware'],
      pros: ['Clean output', 'Fast prototyping'],
      cons: ['React-only'],
      freeTierInfo: '\$5 of included monthly credits, 7 messages/day',
      pricingPlans: [
        PricingPlan(name: 'Team', price: '\$30', period: '/user/month', description: '\$30 credits/user, shared team credits'),
        PricingPlan(name: 'Business', price: '\$100', period: '/user/month', description: '\$30 credits/user, training opt-out'),
        PricingPlan(name: 'Enterprise', price: 'Custom', period: '', description: 'SAML SSO, priority access, SLAs'),
      ],
      trialInfo: 'Free plan available, no credit card required',
      membershipBenefits: ['Deploy to Vercel', 'Design Mode', 'GitHub sync', 'Team collaboration', 'Priority support'],
      plusDiscountPercent: 12,
      proDiscountPercent: 18,
      discountCodePlus: 'AIVERSE-V0-PLUS',
      discountCodePro: 'AIVERSE-V0-PRO',
      createdAt: DateTime(2024, 5, 1),
      updatedAt: DateTime(2024, 6, 19),
    ),
    Tool(
      id: '12',
      name: 'Pika',
      description: "Quick text- and image-to-video with playful effects and ingredients. Great for short-form content.",
      websiteUrl: 'https://pika.art',
      logoUrl: null,
      categoryId: '2',
      tags: ['video', 'short-form'],
      pricingType: PricingType.freemium,
      rating: 4.4,
      viewCount: 178204,
      isTrending: true,
      keyFeatures: ['Pikaffects', 'Ingredients', 'Lip sync'],
      pros: ['Playful', 'Fast'],
      cons: ['Shorter clips'],
      freeTierInfo: '80 monthly video credits',
      pricingPlans: [
        PricingPlan(name: 'Basic', price: '\$8', period: '/month', description: '80 credits/month, 480p only'),
        PricingPlan(name: 'Standard', price: '\$28', period: '/month', description: '700 credits/month, all resolutions'),
        PricingPlan(name: 'Pro', price: '\$76', period: '/month', description: '2,300 credits/month, fastest generations'),
      ],
      trialInfo: 'Free plan available with 80 credits',
      membershipBenefits: ['No watermark', 'Commercial use', 'All Pikaffects', 'Fast generations', 'Priority queue'],
      plusDiscountPercent: 10,
      proDiscountPercent: 15,
      discountCodePlus: 'AIVERSE-PIKA-PLUS',
      discountCodePro: 'AIVERSE-PIKA-PRO',
      createdAt: DateTime(2024, 4, 15),
      updatedAt: DateTime(2024, 6, 17),
    ),
    Tool(
      id: '13',
      name: 'Jasper',
      description: "Brand voice, campaign builder, and 50+ templates aimed at marketing teams.",
      websiteUrl: 'https://jasper.ai',
      logoUrl: null,
      categoryId: '4',
      tags: ['marketing', 'copywriting'],
      pricingType: PricingType.paid,
      rating: 4.3,
      viewCount: 312804,
      keyFeatures: ['Brand voice', 'Campaigns', 'SEO mode'],
      pros: ['Team features', 'Templates'],
      cons: ['Pricey'],
      freeTierInfo: null,
      pricingPlans: [
        PricingPlan(name: 'Pro', price: '\$69', period: '/month', description: '1 seat, Canvas platform, Agents, 2 Brand Voices'),
        PricingPlan(name: 'Pro (Annual)', price: '\$59', period: '/month', description: 'Save ~20% with annual billing'),
        PricingPlan(name: 'Business', price: 'Custom', period: '', description: 'Unlimited Brand Voices, API access, SSO'),
      ],
      trialInfo: '7-day free trial available',
      membershipBenefits: ['Canvas platform', 'Marketing Agents', 'Brand Voice', 'Campaigns', 'Plagiarism checker', 'Browser extension'],
      plusDiscountPercent: 15,
      proDiscountPercent: 20,
      discountCodePlus: 'AIVERSE-JASPER-PLUS',
      discountCodePro: 'AIVERSE-JASPER-PRO',
      createdAt: DateTime(2024, 3, 1),
      updatedAt: DateTime(2024, 6, 14),
    ),
    Tool(
      id: '14',
      name: 'Looka',
      description: "Generate a complete brand identity — logo, palette, social assets — in minutes.",
      websiteUrl: 'https://looka.com',
      logoUrl: null,
      categoryId: '7',
      tags: ['logo', 'brand'],
      pricingType: PricingType.paid,
      rating: 4.3,
      viewCount: 156704,
      keyFeatures: ['Brand kit', 'Mockups', 'Editor'],
      pros: ['End-to-end brand', 'Affordable'],
      cons: ['One-time download fee'],
      freeTierInfo: 'Design logos for free, pay only to download',
      pricingPlans: [
        PricingPlan(name: 'Basic Logo Package', price: '\$20', period: 'one-time', description: 'Low-res logo files'),
        PricingPlan(name: 'Premium Logo Package', price: '\$65', period: 'one-time', description: 'High-res + vector files, full brand kit'),
      ],
      trialInfo: 'Free logo design, pay only when satisfied',
      membershipBenefits: ['High-res logo files', 'Vector EPS/SVG', 'Brand kit', 'Social media kit', 'Business card templates', 'Email signature'],
      plusDiscountPercent: 10,
      proDiscountPercent: 15,
      discountCodePlus: 'AIVERSE-LOOKA-PLUS',
      discountCodePro: 'AIVERSE-LOOKA-PRO',
      createdAt: DateTime(2024, 3, 15),
      updatedAt: DateTime(2024, 6, 13),
    ),
    Tool(
      id: '15',
      name: 'Gamma',
      description: "Type a prompt, get a polished deck, doc, or webpage. Beautiful templates and instant restyles.",
      websiteUrl: 'https://gamma.app',
      logoUrl: null,
      categoryId: '8',
      tags: ['slides', 'decks'],
      pricingType: PricingType.freemium,
      rating: 4.5,
      viewCount: 201403,
      keyFeatures: ['AI generate', 'Restyle', 'Analytics'],
      pros: ['Looks great', 'Fast'],
      cons: ['Limited free exports'],
      freeTierInfo: 'Up to 10 cards per prompt, export to PDF/PPTX',
      pricingPlans: [
        PricingPlan(name: 'Plus', price: '\$10', period: '/month', description: 'Up to 20 cards, remove branding'),
        PricingPlan(name: 'Pro', price: '\$20', period: '/month', description: 'Up to 60 cards, custom branding, API access'),
        PricingPlan(name: 'Ultra', price: '\$30', period: '/month', description: 'Up to 75 cards, most advanced AI models'),
      ],
      trialInfo: 'Free plan available, no credit card required',
      membershipBenefits: ['Remove Gamma branding', 'Advanced AI models', 'Custom domains', 'Analytics', 'API access', 'Workspace templates'],
      plusDiscountPercent: 12,
      proDiscountPercent: 18,
      discountCodePlus: 'AIVERSE-GAMMA-PLUS',
      discountCodePro: 'AIVERSE-GAMMA-PRO',
      createdAt: DateTime(2024, 4, 1),
      updatedAt: DateTime(2024, 6, 16),
    ),
    Tool(
      id: '16',
      name: 'GitHub Copilot',
      description: "Inline completions and chat across every major IDE. Now powered by multiple frontier models.",
      websiteUrl: 'https://github.com/features/copilot',
      logoUrl: null,
      categoryId: '5',
      tags: ['coding', 'ide', 'completion'],
      pricingType: PricingType.paid,
      rating: 4.5,
      viewCount: 612003,
      keyFeatures: ['Multi-model', 'Chat', 'PR summaries'],
      pros: ['Wide IDE support', 'Backed by GitHub'],
      cons: ['Less aggressive than Cursor'],
      freeTierInfo: '2,000 completions/month, 50 chat requests',
      pricingPlans: [
        PricingPlan(name: 'Pro', price: '\$10', period: '/month', description: 'Unlimited completions, cloud agent'),
        PricingPlan(name: 'Pro+', price: '\$39', period: '/month', description: 'Premium models, 4x usage'),
        PricingPlan(name: 'Max', price: '\$100', period: '/month', description: '2.9x Pro+ usage, priority models'),
        PricingPlan(name: 'Business', price: '\$19', period: '/user/month', description: 'IP indemnity, governance'),
        PricingPlan(name: 'Enterprise', price: '\$39', period: '/user/month', description: '2x Business usage, priority support'),
      ],
      trialInfo: 'Free plan available, no credit card required',
      membershipBenefits: ['Unlimited code completion', 'Cloud agent', 'Code review', 'Multi-model support', 'IDE integrations', 'Privacy mode'],
      plusDiscountPercent: 10,
      proDiscountPercent: 15,
      discountCodePlus: 'AIVERSE-COPILOT-PLUS',
      discountCodePro: 'AIVERSE-COPILOT-PRO',
      createdAt: DateTime(2024, 2, 1),
      updatedAt: DateTime(2024, 6, 11),
    ),
    Tool(
      id: '17',
      name: 'Notion AI',
      description: "Summarize, draft, and search across every page in your Notion. Now with Q&A grounded on your docs.",
      websiteUrl: 'https://notion.so/product/ai',
      logoUrl: null,
      categoryId: '9',
      tags: ['notes', 'productivity'],
      pricingType: PricingType.paid,
      rating: 4.4,
      viewCount: 289404,
      keyFeatures: ['Page summarization', 'AI writing', 'Q&A on docs', 'Auto-fill tables'],
      pros: ['Works inside Notion', 'Context-aware'],
      cons: ['Requires Notion subscription', 'Extra cost per seat'],
      freeTierInfo: 'Limited trial of AI capabilities',
      pricingPlans: [
        PricingPlan(name: 'Plus', price: '\$10', period: '/member/month', description: 'Unlimited blocks, 30-day history'),
        PricingPlan(name: 'Business', price: '\$20', period: '/member/month', description: 'Notion Agent, Enterprise Search, SAML SSO'),
        PricingPlan(name: 'Enterprise', price: 'Custom', period: '', description: 'Zero data retention, SCIM, audit log'),
      ],
      trialInfo: 'Free plan available with limited AI trial',
      membershipBenefits: ['AI writing and summarization', 'Enterprise Search', 'Notion Agent', 'Custom Agents', 'SAML SSO', 'Priority support'],
      plusDiscountPercent: 10,
      proDiscountPercent: 15,
      discountCodePlus: 'AIVERSE-NOTION-PLUS',
      discountCodePro: 'AIVERSE-NOTION-PRO',
      createdAt: DateTime(2024, 3, 10),
      updatedAt: DateTime(2024, 6, 15),
    ),
  ];

  final List<Category> _categories = [
    Category(id: '1', name: 'AI Image Generators', description: 'Create stunning visuals from text prompts.', icon: 'image', toolCount: 4, createdAt: DateTime(2024, 1, 1)),
    Category(id: '2', name: 'AI Video Tools', description: 'Generate, edit, and enhance video with AI.', icon: 'video', toolCount: 2, createdAt: DateTime(2024, 1, 1)),
    Category(id: '3', name: 'AI Music Tools', description: 'Compose, remix, and master tracks instantly.', icon: 'music', toolCount: 1, createdAt: DateTime(2024, 1, 1)),
    Category(id: '4', name: 'AI Writing Tools', description: 'Draft, edit, and polish copy at speed.', icon: 'edit', toolCount: 4, createdAt: DateTime(2024, 1, 1)),
    Category(id: '5', name: 'AI Coding Tools', description: 'Pair-program with intelligent assistants.', icon: 'code', toolCount: 4, createdAt: DateTime(2024, 1, 1)),
    Category(id: '6', name: 'AI Voice Generators', description: 'Realistic voiceovers and cloning.', icon: 'mic', toolCount: 1, createdAt: DateTime(2024, 1, 1)),
    Category(id: '7', name: 'AI Logo Makers', description: 'Brand-ready logos in seconds.', icon: 'logo', toolCount: 1, createdAt: DateTime(2024, 1, 1)),
    Category(id: '8', name: 'AI Presentation Tools', description: 'Slides and decks that build themselves.', icon: 'slides', toolCount: 1, createdAt: DateTime(2024, 1, 1)),
    Category(id: '9', name: 'AI Productivity Tools', description: 'Automate the busywork.', icon: 'bolt', toolCount: 1, createdAt: DateTime(2024, 1, 1)),
  ];

  List<Tool> getTools() => List.unmodifiable(_tools);
  List<Category> getCategories() => List.unmodifiable(_categories);

  List<Tool> getTrendingTools() => _tools.where((t) => t.isTrending).toList();
  List<Tool> getFeaturedTools() => _tools.where((t) => t.isFeatured).toList();
  List<Tool> getNewTools() => _tools.where((t) => t.isNew).toList();

  Tool? getToolById(String id) {
    try {
      return _tools.firstWhere((t) => t.id == id);
    } catch (_) {
      return null;
    }
  }

  List<Tool> getToolsByCategory(String categoryId) {
    return _tools.where((t) => t.categoryId == categoryId).toList();
  }

  List<Tool> searchTools(String query) {
    if (query.isEmpty) return [];
    final q = query.toLowerCase();
    return _tools.where((t) => t.name.toLowerCase().contains(q)).toList();
  }
}
